### ISSUE TITLE
A quick thank you

### ISSUE THREAD

**Issue by reflog** [haveyoudebuggedit/gotestfmt#10]
Not an issue, but wanted to drop a note saying thank you for a really useful tool.
I've been frustrated with Go test output in Github CI and this fixed my issues PERFECTLY with just a few lines of cut-n-paste.
THANK YOU

**Comment by janosdebugs** [comment]
Hey @reflog thank you so much for your kind words! An update is coming soon to support multiple packages properly and this will also switch to using JSON output exclusively (see #8). Please be sure to update your config once it's published hopefully later today.
