### ISSUE TITLE
Add example output to the readme

### ISSUE THREAD

**Issue by MadLittleMods** [haveyoudebuggedit/gotestfmt#20]
From the readme, I'm not sure how pretty `gotestfmt` will make the `go test` output since there are no examples.

I do see an example on https://debugged.it/projects/gotestfmt/ linked in the sidebar but took a little bit to notice it there. The screenshot there would be excellent in the readme! 🙂

**Comment by MadLittleMods** [comment]
Ahh, it's a gif in the readme but only plays through once 🤷‍♀️

Feel free to close but still ran into the issue of not knowing.

**Comment by ShadowJonathan** [comment]
Turning the SVG animation into a GIF that loops every so often would be nice, maybe.

**Comment by janosdebugs** [comment]
I don't want to make a GIF because it's huge, but I can make the SVG loop.

**Comment by janosdebugs** [comment]
@MadLittleMods @ShadowJonathan how's this? 

![](https://deploy-preview-18--debugged-it.netlify.app/projects/gotestfmt/gotestfmt.svg)

**Comment by ShadowJonathan** [comment]
maybe a biiiit more time on the logo (like an extra second or so), but this looks good

**Comment by janosdebugs** [comment]
Updated:

![](https://deploy-preview-18--debugged-it.netlify.app/projects/gotestfmt/gotestfmt.svg?v2)

**Comment by janosdebugs** [comment]
Thanks for the feedback!

**Comment by MadLittleMods** [comment]
Thank you @janosdebugs ❤
