### ISSUE TITLE
Coverage is not being applied

### ISSUE THREAD

**Issue by reesmanp** [haveyoudebuggedit/gotestfmt#23]
Using the Github `package.gotpl` file, and running tests via `go test -cover -json -v ./... 2&>1 | gotestfmt -hide empty-packages`, coverage is not output. If I change the `.gotpl` file to this for debugging:

```
{{- /*gotype: github.com/haveyoudebuggedit/gotestfmt/v2/renderer.Package*/ -}}
{{- /*
This template contains the format for an individual package.
*/ -}}
{{- $settings := .Settings -}}
{{- if and (or (not $settings.HideSuccessfulPackages) (ne .Result "PASS")) (or (not $settings.HideEmptyPackages) (ne .Result "SKIP") (ne (len .TestCases) 0)) -}}
    {{- if eq .Result "PASS" -}}
        {{ "\033" }}[0;32m
    {{- else if eq .Result "SKIP" -}}
        {{ "\033" }}[0;33m
    {{- else -}}
        {{ "\033" }}[0;31m
    {{- end -}}
    📦 {{ .Name }}{{ "\033" }}[0m{{- "\n" -}}
    {{- with .Reason -}}
        {{- "  " -}}🛑 {{ . -}}{{- "\n" -}}
    {{- end -}}
    {{- with .Output -}}
        {{- . -}}{{- "\n" -}}
    {{- end -}}
    {{- with .TestCases -}}
        {{- range . -}}
            {{- if or (not $settings.HideSuccessfulTests) (ne .Result "PASS") -}}
                {{- if eq .Result "PASS" -}}
                    {{ "  \033" }}[0;32m✅
                {{- else if eq .Result "SKIP" -}}
                    {{ "  \033" }}[0;33m🚧
                {{- else -}}
                    {{ "  \033" }}[0;31m❌
                {{- end -}}
                {{ " " }}{{- .Name -}}
                {{- "\033" -}}[0;37m ({{ .Duration -}}
                , coverage: {{ . }}%
                {{- "\033" -}}[0m
                {{- "\n" -}}

                {{- with .Output -}}
                    {{- . -}}
                    {{- "\n" -}}
                {{- end -}}
            {{- end -}}
        {{- end -}}
    {{- end -}}
    {{- "\n" -}}
{{- end -}}
```

then I see`<nil>` for the value of coverage. It looks like coverage is not being parsed correctly. I am seeing the event for the coverage as `{"Time":"2021-12-29T12:10:04.616381-08:00","Action":"output","Package":"mypackage","Output":"coverage: 40.7% of statements\n"}`

**Comment by janosdebugs** [comment]
Hey @reesmanp thank you very much. Are you able to provide a full test output? We could integrate it as a full test case.

**Comment by janosdebugs** [comment]
Hey @reesmanp I managed to find the issue, it's in the default template. Could you try the templates in #24 if those work for you? Thanks!

**Comment by reesmanp** [comment]
@janosdebugs thanks for finding it and making a fix. Seems to be working at the module level now.

**Comment by reesmanp** [comment]
I'd recommend removing the package level config outputs since those still don't show.

**Comment by janosdebugs** [comment]
Go doesn't report coverage for individual tests, those will be removed.

**Comment by janosdebugs** [comment]
The fix has now been merged and will be in the next release.
