### ISSUE TITLE
feature request: add a -fail option that will cause gotestfmt to exit with a failing status code if any tests failed

### ISSUE THREAD

**Issue by gabesullice** [haveyoudebuggedit/gotestfmt#33]
I have the following command in my GitHub Action:

```
go test -v -json ./... 2>&1 | gotestfmt
```

I was surprised to see that my action was passing, even though I was sure that a test was failing. When I looked at the output, the test _did_ fail.

That's because the action succeeded since `gotestfmt` exited `0`.

Would you consider adding an optional `-fail` flag that will cause `gotestfmt` to exit with a non-zero exit code if any test fails? That would allow most CI environments to catch failing tests without running them twice.

For now, this is my workaround (ofc, maybe I'm being dumb and there's a much easier solution):

```bash
go test -v -json ./... > output.log && (gotestfmt < output.log && exit 0) || (gotestfmt < output.log && exit 1)
```

**Comment by gabesullice** [comment]
**facepalm** :facepalm: I just saw the `set -euo pipefail` in the docs. That resolves the issue on GitHub. However, I would still like to have that `-fail` option locally.

**Comment by janosdebugs** [comment]
Hey @gabesullice thank you very much for your request. I would still consider your feature request as a "default behavior" since it is easy to miss the `set -euo pipefail` part. Would you mind if I reopened this issue?

**Comment by gabesullice** [comment]
No, not at all :)

**Comment by janosdebugs** [comment]
@gabesullice thank you very much for reporting this, the default behavior starting version 2.3.0 will be to exit with a non-zero status if one or more tests fail. This behavior can be disabled with the `-nofail` option.

**Comment by gabesullice** [comment]
Wow, thank you! That was fast :) open source FTW
