### ISSUE TITLE
GitHub Actions should not be the default output template

### ISSUE THREAD

**Issue by Holek** [haveyoudebuggedit/gotestfmt#4]
This is more of an observation, than an issue. We use `gotestfmt` on CircleCI, but this is true for pretty much all other CIs and command-line usage.

`gotestfmt` should not default to GitHub actions output. What would be great is if `.gotestfmt/package.gotpl` had `::group::` and `::endgroup::` tags removed, and GitHub action for `gotestfmt` had a template switch for GitHub.

![Screenshot 2021-11-09 at 14 40 44](https://user-images.githubusercontent.com/339861/140934772-b662d1d0-2718-409f-ab17-d3f7fa427c9a.png)

Then we could also use `gotestfmt` in our tests, as a test prettifier in terminal, win-win! 🥳

Great job, anyway! Really fun stuff!

And yes, I've read about `.gotestfmt` folder, I just wanted to point out reliance on GitHub Actions by default, rather as an opt-in :)

**Comment by janosdebugs** [comment]
Hey @Holek, you are right. The tool has been written with my very specific needs in mind. If you'd be up for contributing a template for CircleCI, I'd be very happy about a PR. You can add the template to `.gotestfmt/circleci/*.tpl` in this repo, and I can add the code to detect running on CircleCI. I'll move the GitHub code to the `github` folder then.

**Comment by janosdebugs** [comment]
Released as version [v1.1.0](https://github.com/haveyoudebuggedit/gotestfmt/releases/tag/v1.1.0).
