### ISSUE TITLE
Use different icon ⚠️ for "no test files"

### ISSUE THREAD

**Issue by codeliger** [haveyoudebuggedit/gotestfmt#54]
![image](https://github.com/GoTestTools/gotestfmt/assets/9361348/e771b612-3f7e-4603-bb6a-8cddd606c099)

This red stop sign should be reserved for failed tests. 
Maybe a yellow icon ⚠️, or darker color that is easy to ignore but still indicates you have no unit tests for a package.

**Comment by ghost** [comment]
Hey @codeliger you can add your own icons by creating your own templates. Alternatively, please feel free to to submit a pull request to the templates: https://github.com/GoTestTools/gotestfmt/tree/main/.gotestfmt
