### ISSUE TITLE
[bug] delimiter in gotestfmt ----> just intermittent error githubaction

### ISSUE THREAD

**Issue by Kim-Hyo-Bin** [haveyoudebuggedit/gotestfmt#56]
- Describe what the problem is

[libcontainerssh](https://github.com/ContainerSSH/libcontainerssh) Go language version upgrade in progress
look at the github action fail (using gotestfmt)

![image](https://github.com/GoTestTools/gotestfmt/assets/51896679/cdd3fd11-5421-41bc-9fa8-9e15e16422ba)
Error: Process completed with exit code 1.

![image](https://github.com/GoTestTools/gotestfmt/assets/51896679/1b6feb74-d9eb-49a8-92fe-978fc9a60683)
but looking at the log, everything appears normal
and all passed func time is 0s

compare github action
![image](https://github.com/GoTestTools/gotestfmt/assets/51896679/1d7026b3-8b78-411e-9490-2d3d57fa4de6)
it is sucess but 

compare custom environment test
![image](https://github.com/GoTestTools/gotestfmt/assets/51896679/4d380840-fbd3-429c-a750-1838c66f11bd)

same progress and all passed

i will guess
--- PASS: --> part triggers an error and result skip (func test time 0s)
the part below '---' is omitted.

and gotestfmt result using --- or ===

Would it be better to unify the usage of '---' and '===' since they are being used interchangeably?

**Comment by ghost** [comment]
Hi @Kim-Hyo-Bin please post the JSON output of your test so we can properly debug this and create tests for it.

**Comment by Kim-Hyo-Bin** [comment]
> Hi @Kim-Hyo-Bin please post the JSON output of your test so we can properly debug this and create tests for it.

sorry.. forget me....

try again. same code

 
![image](https://github.com/GoTestTools/gotestfmt/assets/51896679/68c5ec76-b03f-4fd5-8ec2-de98be103b6c)

all task passed.
