### ISSUE TITLE
Package misattribution

### ISSUE THREAD

**Issue by janosdebugs** [haveyoudebuggedit/gotestfmt#8]
In the [recent ContainerSSH test run](https://github.com/ContainerSSH/libcontainerssh/runs/4204408554?check_suite_focus=true) the Kubernetes test failures were attributed to the Docker package. The output was the following: https://gist.github.com/janosdebugs/55aae39a95cd781a91eedc265f00c1ec

**Comment by janosdebugs** [comment]
It seems this issue can't be fixed unless `-json` support is added.

**Comment by AlekSi** [comment]
I wonder why you decided to parse `go test` output rather than `go test -json`?

**Comment by janosdebugs** [comment]
@AlekSi I wanted to make it easy to use, but it backfired. :)
